import { makeStyles } from '@material-ui/styles';

export default makeStyles((theme) => {
  return {
    image: {
      '&:hover': {
        backgroundColor: '#5ebe84',
      },
      width: '24px',
      height: '24px',
      objectFit: 'contain',
    },
    box: {
      '&:hover': {
        backgroundColor: '#5ebe84',
      },
      width: '48px',
      height: '48px',
      padding: '23px',
      border: 'solid 12px #dff2e6',
      backgroundColor: '#5ebe84',
      borderRadius: '100%',
      position: 'absolute',
      bottom: '60px',
      left: '270px',
    },
    dot: {
      backgroundColor: '#8f9aa9',
      margin: '0 12px',
      width: '8px',
      height: '8px',
    },
    dotActive: {
      backgroundColor: '#ff9432',
    },
    img: {
      width: '600px',
      height: '240px',
      margin: '0 0 52px',
      objectFit: 'contain',
    },
    title: {
      width: '280px',
      height: '24px',
      fontSize: '20px',
      fontWeight: '800',
      lineHeight: '0.8',
      textAlign: 'center',
      color: '#1d3452',
      margin: '0 auto',
      marginTop: '52px',
      padding: '0',
    },
    content: {
      border: 'none',
      width: '290px',
      height: '56px',
      marginTop: '16px',
      fontSize: '16px',
      lineHeight: '1.75',
      textAlign: 'center',
      color: '#8f9aa9',
      margin: '0 auto',
      letterSpacing: 'normal',
      fontStretch: 'normal',
      overflowY: 'hidden',
      padding: '0',
    },
    actions: {
      padding: '8px',
      display: 'flex',
      justifyContent: 'space-between',
      margin: '0',
    },
    btn: {
      width: '68px',
      height: '28px',
      fontSize: '16px',
      lineHeight: '1.75',
      textAlign: 'left',
      textTransform: 'none',
    },
    Stepper: {
      marginLeft: '44px',
      paddingBottom: '32px',
      padding: '0',
    },
    stepTwoTitle: {
      width: '280px',
      height: '24px',
      fontSize: '20px',
      fontWeight: '800',
      lineHeight: '0.8',
      letterSpacing: 'normal',
      textAlign: 'center',
      color: '#ffffff',
      position: 'absolute',
      top: '71px',
      left: '132px',
    },
    stepTwoContent: {
      border: 'none',
      width: '360px',
      height: '56px',
      marginTop: '16px',
      fontSize: '16px',
      fontWeight: 'normal',
      lineHeight: '1.75',
      textAlign: 'center',
      color: '#ffffff',
      margin: '0 auto',
      letterSpacing: 'normal',
      fontStretch: 'normal',
      overflowY: 'hidden',
      padding: '0',
      position: 'absolute',
      top: '111px',
      left: '120px',
    },
    typo: {
      fontSize: '20px',
    },
    StepperTwo: {
      position: 'absolute',
      bottom: '32px',
      marginLeft: '44px',
    },
    stepTwoBox: {
      '&:hover': {
        backgroundColor: '#5ebe84',
      },
      width: '48px',
      height: '48px',
      padding: '23px',
      border: 'solid 12px #dff2e6',
      backgroundColor: '#5ebe84',
      borderRadius: '100%',
      position: 'absolute',
      bottom: '10px',
      left: '222px',
    },
    WrapperBox: {
      display: 'flex',
      margin: '60px 24px 42px 72px',
      padding: '0',
    },
    imgBox: {
      width: '72px',
      height: '72px',
      borderRadius: '8px',
      backgroundColor: '#f4efff',
      marginRight: '24px',
    },
    textBox: {
      display: 'flex',
      flexDirection: 'column',
      width: '360px',
      height: '72px',
    },
    poter: {
      objectFit: 'contain',
      width: '32px',
      height: '32px',
      margin: '20px',
    },
    pageTwoContent: {
      padding: '0px',
    },
    pageTwoTitle: {
      height: '20px',
      marginBottom: '8px',
      fontSize: '16px',
      fontWeight: '600',
      fontStretch: 'normal',
      fontStyle: 'normal',
      lineHeight: '1.25',
      letterSpacing: 'normal',
      textAlign: 'left',
      color: '#1d3452',
    },
    pageTwoText: {
      width: '360px',
      height: '44px',
      fontSize: '13px',
      fontStretch: 'normal',
      textAlign: 'left',
      fontStyle: 'normal',
      color: 'rgba(29, 52, 82, 0.5)',
      lineHeight: '1.69',
      fontWeight: 'normal',
      letterSpacing: 'normal',
    },
  };
});
